### PR TITLE
src/core: fix GCStashList build macro, which cause charactor storage items disappear

### LINKED ISSUE #61: Character Storage error
Hello, today, check the character storages, I found that the error of disappearing items when you relog still persists, follow the error png...
npc

### PR DESCRIPTION
**Pull request by tiancaiamao**
Close #61 

This is a silly bug, the `__GAME_SERVER__` build macro cause the code not built ...
and then server send wrong GCStashList to the client and the client can't display the items.

### CODE REVIEW

File: src/Core/GCStashList.cpp [hunk 1]
```diff
@@ -336,7 +333,6 @@ void GCStashList::setStashItem(BYTE rack, BYTE index, Item* pItem)
 {
 	__BEGIN_TRY
 
-#ifdef	__GAME_SERVER__
```
Comment (tiancaiamao) [inline src/Core/GCStashList.cpp:339]: Here, the `__GAME_SERVER__` macro is not defined when building this file, so the code is ignored

**Comment by xDezossAx** [comment]
I have the files here with Cpackets, Gpackets, Spackets, and Lpackets, and it worked normally, removing them caused several of these bugs, I couldn't find a way to compile the necessary information, as an example was the @tiancaiamao correction on the issue #66  I will take advantage and see if the problem of calling the bike also works with the folders mentioned above.
